import React from 'react';

const PrivacyPolicy = () => {
  return (
    <article>
      <h1>Privacy Policy</h1>
      <section>
        <p>This privacy policy applies to the Mobile React App Starter (hereby referred to as "Application") for mobile devices that was created by Enes Kaya (hereby referred to as "Service Provider") as a Free service. This service is intended for use "AS IS".</p>
      </section>
      
      <section>
        <h2>Information Collection and Use</h2>
        <p>The Application collects information when you download and use it. This information may include, but is not limited to:</p>
        <ul>
          <li>Your device's Internet Protocol address (e.g., IP address)</li>
          <li>The pages of the Application that you visit, the time and date of your visit, the time spent on those pages, and the operating system you use on your mobile device</li>
        </ul>
        <p>The Application does not gather precise information about the location of your mobile device.</p>
      </section>
      
      <section style={{ display: "none" }}>
        <h2>Location Services</h2>
        <p>The Application collects your device's location to provide personalized content and services.</p>
      </section>
      
      <section>
        <h2>Third Party Access</h2>
        <p>Only aggregated, anonymized data is periodically transmitted to external services to help in improving the Application and service. The Service Provider may share your information with third parties as described in this privacy statement.</p>
        <p>Below are the links to the Privacy Policy of third-party service providers used by the Application:</p>
        <ul>
          <li>
            <a href="https://www.google.com/policies/privacy/" target="_blank" rel="noopener noreferrer">Google Play Services</a>
          </li>
          <li>
            <a href="https://www.facebook.com/about/privacy/update/printable" target="_blank" rel="noopener noreferrer">Facebook</a>
          </li>
        </ul>
      </section>
      
      <section>
        <h2>Opt-Out Rights</h2>
        <p>You can stop all collection of information by the Application by uninstalling it. You may use the standard uninstall processes available as part of your mobile device or via the mobile application marketplace or network.</p>
      </section>
      
      <section>
        <h2>Data Retention Policy</h2>
        <p>The Service Provider will retain User Provided data for as long as you use the Application and for a reasonable time thereafter. If you'd like them to delete User Provided Data, please contact them at enes.kaya95@hotmail.com, and they will respond in a reasonable time.</p>
      </section>
      
      <section>
        <h2>Children</h2>
        <p>The Application does not knowingly collect personally identifiable information from children under 13. If a child under 13 provides personal information, it will be deleted immediately.</p>
      </section>
      
      <section>
        <h2>Security</h2>
        <p>The Service Provider is concerned about safeguarding the confidentiality of your information. They provide physical, electronic, and procedural safeguards to protect information they process and maintain.</p>
      </section>
      
      <section>
        <h2>Changes</h2>
        <p>This Privacy Policy may be updated from time to time. The Service Provider will notify you of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes.</p>
      </section>
      
      <section>
        <h2>Your Consent</h2>
        <p>By using the Application, you are consenting to the processing of your information as set forth in this Privacy Policy now and as amended by us.</p>
      </section>
      
      <section>
        <h2>Contact Us</h2>
        <p>If you have any questions regarding privacy while using the Application, or have questions about the practices, please contact the Service Provider via email at enes.kaya95@hotmail.com.</p>    
        <p>This privacy policy page was generated by <a href="https://app-privacy-policy-generator.nisrulz.com/" target="_blank" rel="noopener noreferrer">App Privacy Policy Generator</a></p>
      </section>
    </article>
  );
};

export default PrivacyPolicy;
